# numpy 编程基础
- NumPy 官网 http://www.numpy.org/
- NumPy 源代码：https://github.com/numpy/numpy
- 科学计算和数据分析的基础包

- 数组是numpy库的中央数据结构。数组是值的网格，它包含有关原始数据，如何定位元素以及如何解释元素的信息。它具有可以以各种方式建立索引的元素网格。元素都是相同的类型，称为array dtype。
- ndarray ('n维数组' 的简写)是numpy的核心概念，它是一系列<span class="burk">同类型数据</span>组成的数组，可以是一维或多维数组
- 结构数组允许异质数组结构 

In [264]:
import numpy as np 
print('''调用numpy 模块或函数时，应该使用np.模块或者函数名称的方式。''')
print("- -"*30)
print('''查看numpy模块内的函数。''')
a = dir(np)
#print(a)
print("- -"*30)
print('''查看numpy模块的版本。''')
np.__version__

调用numpy 模块或函数时，应该使用np.模块或者函数名称的方式。
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
查看numpy模块内的函数。
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
查看numpy模块的版本。


'1.18.1'

# 数组的创建

## 创建一维数组

In [35]:
print("- -"*15,'用普通方法生成一维数组',"- -"*15)  # 分割线
num = [0 for i in range(1,5)]  # 创建一维数组
print(num)  # 打印数组
num1 = ['Li',1,2,3,3.2]
print('列表中的元素类型可以不相同',num1)
print("- -"*15,'下面介绍numpy模块创建数组的方法',"- -"*15)  # 分割线

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 用普通方法生成一维数组 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[0, 0, 0, 0]
列表中的元素类型可以不相同 ['Li', 1, 2, 3, 3.2]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 下面介绍numpy模块创建数组的方法 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -


### arange()方法
- 语法    numpy.arange(start, stop, step, dtype = None)
- 在给定间隔内返回均匀间隔的值，值在包括start但不包括stop的区间,返回的是 ndarray 。

In [38]:
import numpy as np 
v = np.arange(10,dtype=int)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
import numpy as np 
v = np.arange(10,step=2.5,dtype=float)
v.dtype
v

array([0. , 2.5, 5. , 7.5])

### linspace()方法: 产生等差数列
- 语法 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- retstep : bool. If True, return (`samples`, `step`), where `step` is the spacing between samples. retstep会改变计算的输出，输出一个元组，而元组的两个元素分别是需要生成的数列和数列的步进差值。


In [45]:
a = np.linspace(1,19,10)
a

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

###  logspace()方法：产生等比数列

In [147]:
#可直接创建一维的由等比数列组成的数组，可指定开始和结束数值，以及数列包含的数字数量
'''np.logspace(
    start, #序列的起始值
    stop, #序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
    num=50, #要生成的等步长的样本数量，默认为50
    endpoint=True, #该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
    base=10.0,  #对数 log 的底数。
    dtype=None #不再赘述
)
 '''
import numpy as np
from math import e
np.logspace(1,5,5,base=e)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

### 创建对角矩阵数组

In [152]:
'''#可创建对角线矩阵
np.eye(
    N, #指定对角矩阵的行数
    M=None, #指定对角矩阵的列数，默认与N相等
    k=0, #对角线的索引，默认为0，即斜对角，如果赋予正值或负值，则会相对向右上或左下移动
    dtype=float,  #不再赘述
    order='C'
)'''
 
import numpy as np
a = np.eye(5,dtype=int)
a.ndim

2

### 特殊数组：全0/1数组
- zeros数组：全零数组，元素全为零。
- ones数组：全1数组，元素全为1。
- empty数组：创建一个内容随机且依赖于内存状态的向量。
- 以上三个函数均可以产生多元数组。

In [77]:
x = np.zeros(10)
'''语法： zeros(shape, dtype=float, order='C')'''
'''可以产生多元数组如 np.zeros((3,4))'''
#help(np.zeros)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
x = np.ones(20)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [76]:
x1 = np.empty((3,4),np.int)
x1

array([[ 1885941401,  1073308081, -2104352480,  1073094847],
       [ 1507217317,  1072516558,   864273760,  1067754983],
       [ -627551566,  1072153251,  1754293168,  1073418987]])

### 随机数组

In [83]:
print("- -"*15,'高斯分布的随机数(一)',"- -"*15)
'''np.random.randn(d0,d1,...dn)：生成对应的标准的高斯分布随机数'''
print('标准高斯分布的随机数+二维数组',np.random.randn(2,3))

print("- -"*15,'高斯分布的随机数(二)',"- -"*15)
'''np.random.normal(loc, scale, size)：生成均值为loc，标准差为scale，大小为size的高斯分布随机数'''
x = np.random.normal(1,1,10)
print("一般的高斯分布的随机数",x)
x = np.random.normal(1,1,(2,3))
print("一般的高斯分布的随机数+二维数组",x)

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 高斯分布的随机数(一) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
标准高斯分布的随机数+二维数组 [[ 1.02451632  2.14325302 -0.96544785]
 [-0.25607679  1.12515145 -0.40051724]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 高斯分布的随机数(二) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
一般的高斯分布的随机数 [-0.93870094 -0.52932362  1.74854311  0.49922881  1.28462598  0.92733802
  0.42558788  0.44365482  0.97052676  1.54326362]
一般的高斯分布的随机数+二维数组 [[ 1.67724202  2.52283387  1.88909515]
 [ 0.59776421 -0.13757208  2.13721878]]


In [85]:
print("- -"*15,'均匀分布的随机数(一)',"- -"*15)
'''np.random.rand(shape)：生成对应形状（shape）的[0,1]均匀分布的随机数'''
x = np.random.rand(2,3)
print(x)
print("- -"*15,'均匀分布的随机数(二)',"- -"*15)
'''np.random.uniform(low, high, size)：生成一个从[low, high)中随即采样的，样本数量为size的均匀分布随机数'''
x1 = np.random.uniform(0,1,10)
print(x1)
'''如何产生其它分布的随机数？'''

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 均匀分布的随机数(一) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[[0.74545452 0.20294491 0.20069759]
 [0.14923271 0.75442628 0.70120174]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 均匀分布的随机数(二) - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[0.4427768  0.28877574 0.4876246  0.06657145 0.47267468 0.27346376
 0.81062662 0.56814251 0.34885429 0.36801066]


'如何产生其它分布的随机数？'

## 二维数组

In [106]:
'''普通方法生成'''
num = [[1 for i in range(1,5)]for j in range(1,5)]
print(num)  # 打印数组
print("- -"*50)  # 分割线

'''等价的方法'''
np.ones((4,4),dtype=int)

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]
--------------------------------------------------


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [154]:
#一般使用array构造函数创建ndarray
print('''import numpy as np
np.array(
    object, #传入列表、元组来创建一维数组，或列表、元组的嵌套创建多维数组
    dtype = None, #设置数组元素的数据类型，可以是内置的数据类型，也可是自定义的结构化数据类型
    copy = True,  #设置传入的对象是否需要复制，默认是True，如果设置为False，则会直接引用，一般用不到
    order = None, #设置创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）,一般无需显示设置
    subok = False, #默认返回一个与基类类型一致的数组，暂时还未用到过
    ndmin = 0 #指定生成数组的最小维度，如果传入的object维度没达到最小维度，则会自定转变为最小维度的数组
)''')

import numpy as np
np.array(
    object, #传入列表、元组来创建一维数组，或列表、元组的嵌套创建多维数组
    dtype = None, #设置数组元素的数据类型，可以是内置的数据类型，也可是自定义的结构化数据类型
    copy = True,  #设置传入的对象是否需要复制，默认是True，如果设置为False，则会直接引用，一般用不到
    order = None, #设置创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）,一般无需显示设置
    subok = False, #默认返回一个与基类类型一致的数组，暂时还未用到过
    ndmin = 0 #指定生成数组的最小维度，如果传入的object维度没达到最小维度，则会自定转变为最小维度的数组
)


In [118]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
print(m1)
print("- -"*15,'array要求数据的类型相同',"- -"*15) 
m2= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19),['li','liu','zhang']])  
print(m2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - array要求数据的类型相同 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['10' '11' '12']
 ['13' '14' '15']
 ['16' '17' '18']
 ['li' 'liu' 'zhang']]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 描述数据的元组数据组成 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
(6, 3)
2
44


## 结构数组

In [137]:
name = ['Alice','Bob','Cathy','Doug']
age = [25,45,37,19]
weight = [55.0, 85.5, 68.0, 61.5]
dict(姓名=name,年龄=age,体重=weight)


{'姓名': ['Alice', 'Bob', 'Cathy', 'Doug'],
 '年龄': [25, 45, 37, 19],
 '体重': [55.0, 85.5, 68.0, 61.5]}

In [138]:
'''numpy 模块如何存储不同类型的数据?

结构化数组的数据类型有多种制定方式：'''
# 1. 采用字典的方法：两个键：names(定义每个字段的名称)和formats（）定义每个字段的类型
array1 = np.dtype({'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})
print(array1)
# 2. 数值数据类型可以用Python类型和Numpy的dtype类型指定：
array2 = np.dtype({'names':('name', 'age', 'weight'),'formats':((np.str_, 10), int, np.float32)})
print(array2)
# 3. 使用元组的方式：
array3 = np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])
print(array3)
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype =array1) 
print(a)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]
[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')]
[('abc', 21, 50.) ('xyz', 18, 75.)]


## 从已有的数据创建数组

In [141]:
print('''np.asarray(a, dtype = None, order = None)
a:任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，
多维数组
order: "C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。''')

np.asarray(a, dtype = None, order = None)
a:任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，
多维数组
order: "C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。


In [287]:
x =  [(1,2,3),(4,5)] 
a = np.asarray(x)  
print (a)
a.shape
a.ndim
print(np.array(x))

[(1, 2, 3) (4, 5)]
[(1, 2, 3) (4, 5)]


# 索引和切片

## 基本索引与切片

In [163]:
'''因矩阵或数组，其实本质是由列表组成，故也可以使用与访问Python列表元素相同的方式对数组进行切片和索引访问。'''
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [176]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组

In [181]:
'''1、使用索引切片访问和提取数组的一部分'''
print('- -'*5,'提取1到6行每隔1行取一行，及1到2列的数据','- -'*5)

print(m1[0:5:2,0:2]) #会并组成一个2*3矩阵

'''2、提取指定的行、列: 用，表示不同的维度'''
print('- -'*5,'提取第3行的数据','- -'*5)
print(m1[2,:]) 
print('- -'*5,'提取第3列','- -'*5)
print(m1[:,2])

'''3、提取指定的元素''' 
print('- -'*5,'提取第2行的第二列元素','- -'*5)
print(m1[1,1])
 
'''4、一维及更高维，同理，比如提取shape为3*4*5的矩阵，则即a[k,m,n]，其中京k、m、n即可以是索引值，也可以是由索引值构成的切片'''
'''5、切片中省略号的用法''' 

print('- -'*5,'当要提取某一整行或整列时，其效果与：完全相同','- -'*5)
print('m1[:,2] 等同于m1[...,2]:即提取数组的第二列数据\n',m1[...,2])

print('m1[2,:] 等同于m1[2,...]:即提取数组的第二行数据\n',m1[2,...])

 
'''6、切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。'''
s=slice(1,3)
m1[s] #等同于m1[1:3]

- -- -- -- -- - 提取1到6行每隔1行取一行，及1到2列的数据 - -- -- -- -- -
[[ 1  2]
 [ 7  8]
 [13 14]]
- -- -- -- -- - 提取第3行的数据 - -- -- -- -- -
[7 8 9]
- -- -- -- -- - 提取第3列 - -- -- -- -- -
[ 3  6  9 12 15 18]
- -- -- -- -- - 提取第2行的第二列元素 - -- -- -- -- -
5
- -- -- -- -- - 当要提取某一整行或整列时，其效果与：完全相同 - -- -- -- -- -
m1[:,2] 等同于m1[...,2]:即提取数组的第二列数据
 [ 3  6  9 12 15 18]
m1[2,:] 等同于m1[2,...]:即提取数组的第二行数据
 [7 8 9]


slice(1, 3, None)

## 花式索引访问
- 指利用整数数组进行索引，使用指定顺序对数组提取子集。
- 使用一维整型数组作为索引时，
  如果目标是一维数组，那么索引的结果就是对应位置的元素（类似索引访问）；
  如果目标是二维数组，那么就是对应下标的行（类似直接取对应的行）

In [182]:
'''1.原数组为一维数组，传入1个一维数组作为索引.'''
a=np.array([1,2,3,4,5,6])
a[[1,2,3]] #得到a的第2、3、4个元素并组成一个新的一维数组

array([2, 3, 4])

In [201]:
'''2.原数组为二维数组，传入1个一维数组作为索引'''
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a[[1,2]] #得到a的第2和第3行组成的2*3数组


array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
'''3.原数组为多维数组，传入多个一维数组作为索引'''
b = np.arange(24).reshape(2,3,4)
print(b)
print("- -"*5, '提取第0层第1行第2列、第0层第2行第3列的数据集','- -'*10)
index = [[0],[1,2],[2,3]]#将被弃用
#b[index]
index = ([0],[1,2],[2,3])#将多个一维数组放在元组内；层，行列，行列
print(b[index])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
- -- -- -- -- - 提取第0层第1行第2列、第0层第2行第3列的数据集 - -- -- -- -- -- -- -- -- -- -
[ 6 11]


In [221]:
'''4. 原数组为多维数组，传入多个一维数组作为索引，且使用ix_ 函数
ix_函数将多个一维数组转换为一个用于选取矩形区域的索引器
#pandas内的iloc索引方式，其本质即ix_的索引方式'''
index = np.ix_([0],[1,2],[2,3]) #层，行，列
print(b[index])
print("- -"*5, '''第0层的第1行的第2列和第3列,和第2行的的第2列和第3列元素''','- -'*10)

[[[ 6  7]
  [10 11]]]
- -- -- -- -- - 第0层的第1行的第2列和第3列,和第2行的的第2列和第3列元素 - -- -- -- -- -- -- -- -- -- -


In [212]:
index1 = np.ix_([1,0],[2,1],[0,3,2])
b[index1]

array([[[20, 23, 22],
        [16, 19, 18]],

       [[ 8, 11, 10],
        [ 4,  7,  6]]])

## 逻辑索引
- 使用布尔型索引、条件索引

In [222]:
b = np.arange(24).reshape(2,3,4)
b[b>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [227]:
b = np.arange(24).reshape(2,3,4)
b[~(b>=15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [232]:
b = np.arange(24).reshape(2,3,4)
b[(b<20)&(b>=15)]
b[(b>20)|(b>=15)]
'''and 和 or 布尔数组中无效'''

'and 和 or 布尔数组中无效'

In [233]:
'''
#布尔索引，可以使用布尔表达式（条件表达式）来检索出某个数组符合指定条件的元素，并返回由这些元素组成的一维数组

#布尔索引在理解pandas相关条件检索操作时，很有用，可以说pandas的条件检索，本质就是布尔索引

#其本质的运算逻辑即对数组进行遍历，找出满足条件的元素对应的索引值，最后返回索引值对应的元素
'''

'\n#布尔索引，可以使用布尔表达式（条件表达式）来检索出某个数组符合指定条件的元素，并返回由这些元素组成的一维数组\n\n#布尔索引在理解pandas相关条件检索操作时，很有用，可以说pandas的条件检索，本质就是布尔索引\n#其本质的运算逻辑即对数组进行遍历，找出满足条件的元素对应的索引值，最后返回索引值对应的元素\n'

# 数组的属性

In [123]:
import numpy as np
m1= np.array([np.arange(1,4),np.arange(4,7),np.arange(7,10),np.arange(10,13),np.arange(13,16),np.arange(16,19)])  # 创建6行3列的二维数组
#print(m1)
print("- -"*15,'数组的属性',"- -"*15) 
print(m1.shape)#shape属性表示数组的形状
print(m1.ndim)#ndim属性表示数组的维数
print(m2.itemsize)#itemsize 属性表示元素大小：即该数组内元素占据内存大小，字节单位

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 数组的属性 - -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
(6, 3)
2
44


In [125]:
print('''其它的数组属性
ndarray.ndim	秩，即轴的数量或维度的数量
ndarray.shape	数组的维度，对于矩阵，n 行 m 列
ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype	ndarray 对象的元素类型
ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags	ndarray 对象的内存信息
ndarray.real	ndarray元素的实部
ndarray.imag	ndarray 元素的虚部
ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。''')

其它的数组属性
ndarray.ndim	秩，即轴的数量或维度的数量
ndarray.shape	数组的维度，对于矩阵，n 行 m 列
ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype	ndarray 对象的元素类型
ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags	ndarray 对象的内存信息
ndarray.real	ndarray元素的实部
ndarray.imag	ndarray 元素的虚部
ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。


#  数组操作

numpy 中包含了一些函数用于处理数组，大概可分为以下几类：

- 修改数组形状
- 翻转数组
- 修改数组维度
- 连接数组
- 分割数组
- 数组元素的添加与删除

## 修改数组形状

In [235]:
print('''
函数	描述
reshape	不改变数据的条件下修改形状
flat	数组元素迭代器
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ravel	返回展开数组''')


函数	描述
reshape	不改变数据的条件下修改形状
flat	数组元素迭代器
flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
ravel	返回展开数组


In [236]:
print('''np.reshape 函数可以在不改变数据的条件下修改形状，格式如下： 
          np.reshape(arr, newshape, order='C')
arr：要修改形状的数组
newshape：整数或者整数数组，新的形状应当兼容原有形状
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。''')

np.reshape 函数可以在不改变数据的条件下修改形状，格式如下： 
          np.reshape(arr, newshape, order='C')
arr：要修改形状的数组
newshape：整数或者整数数组，新的形状应当兼容原有形状
order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。


In [242]:
import numpy as np 
a = np.arange(10)
print ('原始数组：',a,'\n')
print("- -"*20) 
b = a.reshape(2,5)
print ('修改后的数组：\n',b)

原始数组： [0 1 2 3 4 5 6 7 8 9] 

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
修改后的数组：
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [255]:
import numpy as np
 
a = np.arange(10).reshape(2,5) 
print ('原始数组：')
for row in a:
    print (row)
print("- -"*30)  
print(a.flat)

原始数组：
[0 1 2 3 4]
[5 6 7 8 9]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -


In [ ]:
'''对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：'''
print ('迭代后的数组：')
for element in a.flat:
    print (element)

In [265]:
print('''numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：

ndarray.flatten(order='C')
参数说明：

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。''')

numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：

ndarray.flatten(order='C')
参数说明：

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。


In [266]:
import numpy as np
 
a = np.arange(10).reshape(2,5)
 
print ('原数组：',a)
print("- -"*30) 

print ('展开的数组：',a.flatten())
print("- -"*30) 
 
print ('以 F 风格顺序展开的数组：',a.flatten(order = 'F'))


原数组： [[0 1 2 3 4]
 [5 6 7 8 9]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
展开的数组： [0 1 2 3 4 5 6 7 8 9]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
以 F 风格顺序展开的数组： [0 5 1 6 2 7 3 8 4 9]


## 反转数组

In [270]:
print('''
函数	           描述
transpose	对换数组的维度
ndarray.T	和 self.transpose() 相同
rollaxis	向后滚动指定的轴
swapaxes	对换数组的两个轴''')


函数	           描述
transpose	对换数组的维度
ndarray.T	和 self.transpose() 相同
rollaxis	向后滚动指定的轴
swapaxes	对换数组的两个轴


In [271]:
print('''numpy.transpose 函数用于对换数组的维度，格式如下：

         numpy.transpose(arr, axes)
参数说明:
arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。''')

numpy.transpose 函数用于对换数组的维度，格式如下：

         numpy.transpose(arr, axes)
参数说明:
arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。


In [273]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
print ('原数组：\n',a)
print("- -"*30)
b = np.transpose(a) 
print ('反转数组：')
print (b)

原数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 数组整合

In [274]:
print('''
函数	            描述
concatenate	   连接沿现有轴的数组序列
stack	       沿着新的轴加入一系列数组。
hstack	       水平堆叠序列中的数组（列方向）
vstack	       竖直堆叠序列中的数组（行方向）''')


函数	            描述
concatenate	   连接沿现有轴的数组序列
stack	       沿着新的轴加入一系列数组。
hstack	       水平堆叠序列中的数组（列方向）
vstack	       竖直堆叠序列中的数组（行方向）


### 水平组合
- hstack 函数
- concatenate函数

In [285]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)
print("- -"*30,'行数相同')
h_ab = np.hstack((a,b))
print("hstack函数处理的对象是元组,所以需要两层括号:\n",h_ab)

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 行数相同
hstack函数处理的对象是元组,所以需要两层括号:
 [[1 2 5 6]
 [3 4 7 8]]


In [275]:
print('''
np.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：
               np.concatenate((a1, a2, ...), axis)
参数说明：

a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0''')


np.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：
               np.concatenate((a1, a2, ...), axis)
参数说明：

a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0


In [278]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)

print ('\n')
# 两个数组的维度相同
 
print ('沿轴 1 连接两个数组：行数相同')
print (np.concatenate((a,b),axis = 1))

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


### 垂直组合

In [283]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：',a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：',b)
print ('\n')
print("- -"*30)
print ('竖直堆叠：列数相同')
v_ab = np.vstack((a,b))
print (v_ab)

第一个数组： [[1 2]
 [3 4]]


第二个数组： [[5 6]
 [7 8]]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [282]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：\n',a)

print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：\n',b)

print ('\n')

 
print ('沿轴 0 连接两个数组：列数应该相同')
print (np.concatenate((a,b)))
print ('\n')

第一个数组：
 [[1 2]
 [3 4]]


第二个数组：
 [[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




## 分割数组

In [288]:
print('''
函数	  数组及操作
split	将一个数组分割为多个子数组
hsplit	将一个数组水平分割为多个子数组（按列）
vsplit	将一个数组垂直分割为多个子数组（按行）''')


函数	  数组及操作
split	将一个数组分割为多个子数组
hsplit	将一个数组水平分割为多个子数组（按列）
vsplit	将一个数组垂直分割为多个子数组（按行）


In [290]:
print('''
np.split 函数沿特定的轴将数组分割为子数组，格式如下：

np.split(ary, indices_or_sections, axis)
参数说明：

ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：设置沿着哪个方向进行切分，默认为 0，横向切分，即水平方向。为 1 时，纵向切分，即竖直方向。''')


np.split 函数沿特定的轴将数组分割为子数组，格式如下：

np.split(ary, indices_or_sections, axis)
参数说明：

ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：设置沿着哪个方向进行切分，默认为 0，横向切分，即水平方向。为 1 时，纵向切分，即竖直方向。


In [298]:
import numpy as np
 
a = np.arange(9)
 
print ('第一个数组：',a)
print("- -"*30)
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
print("- -"*30) 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)
print ('\n')
print("- -"*30) 
print('split 返回的是一个列表：', type(b))

第一个数组： [0 1 2 3 4 5 6 7 8]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
split 返回的是一个列表： <class 'list'>


In [310]:
import numpy as np

a = np.arange(16).reshape(4, 4)
print('第一个数组：')
print(a)
print('\n')
print('默认分割（0轴）：')
b = np.split(a,2)
print(b)
print('\n')

print('沿垂直方向分割：')
c = np.split(a,2,1)
print(c)
print('\n')



第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


默认分割（0轴）：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


沿垂直方向分割：
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


##  数组元素的添加与删除

In [311]:
print('''
函数	     元素及描述
resize	返回指定形状的新数组
append	将值添加到数组末尾
insert	沿指定轴将值插入到指定下标之前
delete	删掉某个轴的子数组，并返回删除后的新数组
unique	查找数组内的唯一元素''')


函数	     元素及描述
resize	返回指定形状的新数组
append	将值添加到数组末尾
insert	沿指定轴将值插入到指定下标之前
delete	删掉某个轴的子数组，并返回删除后的新数组
unique	查找数组内的唯一元素


In [312]:
print('''np.resize 函数返回指定大小的新数组。

如果新数组大小大于原始大小，则包含原始数组中的元素的副本。

numpy.resize(arr, shape)
参数说明：

arr：要修改大小的数组
shape：返回数组的新形状'''
)

np.resize 函数返回指定大小的新数组。

如果新数组大小大于原始大小，则包含原始数组中的元素的副本。

numpy.resize(arr, shape)
参数说明：

arr：要修改大小的数组
shape：返回数组的新形状
第一个数组：
[[1 2 3]
 [4 5 6]]


第一个数组的形状：
(2, 3)


第二个数组：
[[1 2]
 [3 4]
 [5 6]]


第二个数组的形状：
(3, 2)


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [313]:
import numpy as np
 
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的形状：')
print (a.shape)
print ('\n')
b = np.resize(a, (3,2))
 
print ('第二个数组：',b)

print ('\n')
 
print ('第二个数组的形状：')
print (b.shape)
print ('\n')
# 要注意 a 的第一行在 b 中重复出现，因为尺寸变大了
 
print ('修改第二个数组的大小：')
b = np.resize(a,(3,3))
print (b)

第一个数组：
[[1 2 3]
 [4 5 6]]


第一个数组的形状：
(2, 3)


第二个数组： [[1 2]
 [3 4]
 [5 6]]


第二个数组的形状：
(3, 2)


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]
