# numpy 编程基础(续)

- matrix 是 numpy 提供的另外一种数据类型
- matrix 是继承自 numpy 的二维 ndarray 对象，不仅具有二维ndarray 的属性、方法与函数，还拥有诸多特有的属性与方法. 

## 创建numpy矩阵

In [30]:
print('- -'*20,'''使用mat 、matrix或者bmat 函数创建矩阵''','- -'*10)

print('= = '*10,'''matrix()的语法''','= ='*10)
print('''np.matrix(data，dtype = None，copy = True )
          data: 数组的对象或数据字符串.如果data为字符串，则将其解释为矩阵，其中用逗号或空格分隔列，用分号分隔行.
          dtype:输出矩阵的数据类型。
          copy:如果data已经是ndarray，则此标志确定是否复制数据（默认值）或是否构造了视图。
                              ''')
import numpy as np
print('- -'*20,'''字符串矩创建矩阵（一）''','- -'*10)
mat1 = np.matrix('1,2,3;4,5,6;7,8,9')
print("mat1:\n",mat1)
print('- -'*20,'''字符串矩创建矩阵（二）''','- -'*10)
mat2 = np.matrix('1 2 3;4 5 6;7 8 9')
print("mat2:\n",mat2)
print('- -'*20,'''数组创建矩阵''','- -'*10)
mat3 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("mat3:\n",mat3)

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 使用mat 、matrix或者bmat 函数创建矩阵 - -- -- -- -- -- -- -- -- -- -
= = = = = = = = = = = = = = = = = = = =  matrix()的语法 = == == == == == == == == == =
np.matrix(data，dtype = None，copy = True )
          data: 数组的对象或数据字符串.如果data为字符串，则将其解释为矩阵，其中用逗号或空格分隔列，用分号分隔行.
          dtype:输出矩阵的数据类型。
          copy:如果data已经是ndarray，则此标志确定是否复制数据（默认值）或是否构造了视图。
                              
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 字符串矩创建矩阵（一） - -- -- -- -- -- -- -- -- -- -
mat1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 字符串矩创建矩阵（二） - -- -- -- -- -- -- -- -- -- -
mat2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- - 数组创建矩阵 - -- -- -- -- -- -- -- -- -- -
mat3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
'''大块矩阵的连接'''
import numpy as np
ar1 = np.eye(3);print(ar1)
ar2 = 3*ar1;print(ar2)
mat = np.bmat("ar1 ar2; ar1 ar2")
mat
#help(np.bmat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


matrix([[1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.],
        [1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.]])

## 矩阵的属性和基本运算

In [9]:
import numpy as np
mat =np.matrix(np.arange(4).reshape(2,2))
mT = mat.T #转置
mH=mat.H#共轭转置
mI=mat.I #逆矩阵
print(mT,'\n',mH,'\n',mI)

[[0 2]
 [1 3]] 
 [[0 2]
 [1 3]] 
 [[-1.5  0.5]
 [ 1.   0. ]]


In [41]:
'''使用matmul来实现两个矩阵的乘法计算，数学公式如下所示。

Cm×q=Am×q×Bq×n 注意两矩阵能相乘，要求A的列等于B的行。'''

import numpy as np
a = np.arange(1, 7).reshape([2, 3])
b = np.arange(2, 8).reshape([3, 2])
print(a)
print('- -'*30)
print(b)
print(np.matmul(a, b),"# matmul(a, b)")

[[1 2 3]
 [4 5 6]]
- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
[[2 3]
 [4 5]
 [6 7]]
[[28 34]
 [64 79]] # matmul(a, b)


In [ ]:
'''numpy.linalg模块，提高供线性代数所需要的功能，如计算逆矩阵、求解线性方程组、求特征值、奇异值分解及求解行列式'''

In [10]:
mat = np.mat('1 1 1;1 2 3;1 3 6')
inverse = np.linalg.inv(mat)
A = np.dot(mat,inverse)
A

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
mat = np.mat('1 -1 1;2 1 0;2 1 -1')
b =np.array([4,3,-1])
x = np.linalg.solve(mat,b)
x

array([1., 1., 4.])

In [ ]:

mat = np.mat('1 -0 2;0 3 0;2 0 1')
mat_value,mat_vector =np.linalg.eig(A)

In [19]:
import numpy as np
A = np.mat('4.0,11.0,14.0;8.0,7.0,-2.0')
U,Sigma,V =np.linalg.svd(A,full_matrices=False)
U,Sigma,V


(matrix([[-0.9486833 , -0.31622777],
         [-0.31622777,  0.9486833 ]]),
 array([18.97366596,  9.48683298]),
 matrix([[-0.33333333, -0.66666667, -0.66666667],
         [ 0.66666667,  0.33333333, -0.66666667]]))

In [20]:
import numpy as np
A = np.mat('3 4;5 6')
a =np.linalg.det(A)
a

-2.0000000000000004

In [38]:
import numpy as np
x = np.array([1, 0, -2])
n0 = np.linalg.norm(x, ord = 0)
print( n0)
import numpy as np
x = np.array([2, 0, -4])
n1 = np.linalg.norm(x, ord = 1)
import numpy as np
x = np.array([3, 0, -4])
n = np.linalg.norm(x, ord = np.inf)#所有向量元素绝对值中的最大值。
import numpy as np
x = np.array([3, 0, -4])
n2 = np.linalg.norm(x, ord = 2)

2.0


## 文件读写

### 读写 txt 或 csv 文件

In [26]:
import numpy as np

a = np.array(range(20)).reshape((4, 5))
print(a)

# 后缀改为 .txt 一样
filename = 'a.csv'
# 写文件
np.savetxt(filename, a, fmt='%d', delimiter=',')

# 读文件
b = np.loadtxt(filename, dtype=np.int32, delimiter=',')
print(b)
'''只能保存一维和二维 numpy 数组，当 numpy 数组 a 有多维时，需要将其 a.reshape((a.shape[0], -1)) 后才能用这种方式保存。
不能追加保存，即每次 np.savetxt() 都会覆盖之前的内容。'''

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


'只能保存一维和二维 numpy 数组，当 numpy 数组 a 有多维时，需要将其 a.reshape((a.shape[0], -1)) 后才能用这种方式保存。\n不能追加保存，即每次 np.savetxt() 都会覆盖之前的内容。'

### 读写 npy 或 npz 文件

In [28]:
import numpy as np

a = np.array(range(20)).reshape((2, 2, 5))
print(a)

filename = 'a.npy'
# 写文件
np.save(filename, a)

# 读文件
b = np.load(filename)
print(b)
print(b.shape)
'''优点：

npy 文件可以保存任意维度的 numpy 数组，不限于一维和二维；
npy 保存了 numpy 数组的结构，保存的时候是什么 shape 和 dtype，取出来时就是什么样的 shape 和 dtype。
缺点：

只能保存一个 numpy 数组，每次保存会覆盖掉之前文件中存在的内容（如果有的话）。'''

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
(2, 2, 5)


'优点：\n\nnpy 文件可以保存任意维度的 numpy 数组，不限于一维和二维；\nnpy 保存了 numpy 数组的结构，保存的时候是什么 shape 和 dtype，取出来时就是什么样的 shape 和 dtype。\n缺点：\n\n只能保存一个 numpy 数组，每次保存会覆盖掉之前文件中存在的内容（如果有的话）。'

In [29]:
import numpy as np

a = np.array(range(20)).reshape((2, 2, 5))
b = np.array(range(20, 44)).reshape(2, 3 ,4)
print('a:\n', a)
print('b:\n', b)

filename = 'a.npz'
# 写文件， 如果不指定key，那么默认key为'arr_0'、'arr_1'，一直排下去。
np.savez(filename, a, b=b)

# 读文件
c = np.load(filename)
print('keys of NpzFile c:\n', c.keys())
print("c['arr_0']:\n", c['arr_0'])
print("c['b']:\n", c['b'])
'''优点：

npy 文件可以保存任意维度的 numpy 数组，不限于一维和二维；
npy 保存了 numpy 数组的结构，保存的时候是什么 shape 和 dtype，取出来时就是什么样的 shape 和 dtype；
可以同时保存多个 numpy 数组；
可以指定保存 numpy 数组的 key，读取的时候很方便，不会混乱。
缺点：

保存多个 numpy 数组时，只能同时保存，即 np.savez(filename, a, b=b)。每次保存会覆盖掉之前文件中存在的内容（如果有的话）。'''

a:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
b:
 [[[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]]]
keys of NpzFile c:
 KeysView(<numpy.lib.npyio.NpzFile object at 0x000001CDB537B208>)
c['arr_0']:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
c['b']:
 [[[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]]]


'优点：\n\nnpy 文件可以保存任意维度的 numpy 数组，不限于一维和二维；\nnpy 保存了 numpy 数组的结构，保存的时候是什么 shape 和 dtype，取出来时就是什么样的 shape 和 dtype；\n可以同时保存多个 numpy 数组；\n可以指定保存 numpy 数组的 key，读取的时候很方便，不会混乱。\n缺点：\n\n保存多个 numpy 数组时，只能同时保存，即 np.savez(filename, a, b=b)。每次保存会覆盖掉之前文件中存在的内容（如果有的话）。'

In [34]:
print('''矩阵matrix和array的区别主要有两点：

1). 乘法规则有所不同， 如果是array那么乘法是对应元素的乘积作为结果对应位置上的值，
而如果是matrix则需要满足第一个矩阵的列等于第二个矩阵的行的要求才能乘。''')

矩阵matrix和array的区别主要有两点：

1). 乘法规则有所不同， 如果是array那么乘法是对应元素的乘积作为结果对应位置上的值，
而如果是matrix则需要满足第一个矩阵的列等于第二个矩阵的行的要求才能乘。


In [37]:
import numpy as np
a = np.arange(12).reshape([3, 4])
b = np.arange(12).reshape([4, 3])
# wrong
#print a * b
print ("multi\n", a * b.T,type(a))
print ("matrix multi\n", np.matmul(a, b))
print('\n')
'''和b都是ndarray数组，a * b.T是数组相乘，要求*前后的操作数的shape必须是一致。而matmul(a, b)则是把第一个形参a和b看作矩阵做矩阵的乘法，
要求a的列等与b的行。 x和y是matrix，x * y.T等价于matmul函数。 '''
x = np.matrix([[1, 3, 5], [2, 4, 6]])
print(x, x.shape,type(x), "# x.shape")
y = np.matrix([[7, 9, 11], [8, 10, 12]])
print(y, y.shape, "# y.shape")
# wrong 
#print x * y
print('\n')
print( x * y.T, "# x * y.T")
print(np.matmul(x, y.T), "# np.matmul(x, y.T)")
print(np.multiply(x, y), "# matrix multiply")

multi
 [[  0   3  12  27]
 [  4  20  42  70]
 [ 16  45  80 121]] <class 'numpy.ndarray'>
matrix multi
 [[ 42  48  54]
 [114 136 158]
 [186 224 262]]


[[1 3 5]
 [2 4 6]] (2, 3) <class 'numpy.matrix'> # x.shape
[[ 7  9 11]
 [ 8 10 12]] (2, 3) # y.shape


[[ 89  98]
 [116 128]] # x * y.T
[[ 89  98]
 [116 128]] # np.matmul(x, y.T)
[[ 7 27 55]
 [16 40 72]] # matrix multiply


In [36]:
'''2). 数组和矩阵的shape不同。'''
import numpy as np
w = np.array([1, 2, 4])
print( "ndarray", w.shape,w.T.shape)
v = np.matrix([1, 2, 4])
print( "matrix ", v.shape,v.T.shape)

ndarray (3,) (3,)
matrix  (1, 3) (3, 1)
